### PR TITLE
Add ability gather items within folders

### PR DESCRIPTION
**Pull request by ciphercules**
This feature adds the ability to pull lastpass values that exist in folders

```
key: ((Shared-folder/credential/Notes))
```

We need this in order to move our pipeline over to Wings and share the credentials used in the pipeline without having to save them to disk. 

cc: @wayneadams

### CODE REVIEW

**Comment by thausler786** [comment]
This passes the current test suites in the application.  However, when we attempt to configure our own pipeline using a binary compiled from this PR many of the keys from Lastpass are not interpolated correctly.

Looking at the code, this changes existing behavior to require specifying the folder, which we believe is the cause of the break we are seeing.

We tried prefixing all of our credentials with the folder and we got fewer failed interpolations.  We have an additional hypothesis that [this line](https://github.com/pivotal-cf/reconfigure-pipeline/blob/80defc1d88876ab78b2bdcb591af90fcbc940349/lastpass/processor.go#L101) does not correctly quote the arguments to the command it is shelling out, and so if the folder name has spaces in it the lastpass CLI errors (yes, we are monsters).

We can't merge this today, but we welcome proposals that could mitigate these problems. We're glad to work with you to get some test cases written that protect these behaviors against regression.

**Comment by thausler786** [comment]
Upon further inspection, the behavior we see is this:
1.  If we don't include the folder name, all interpolations fail
2. If we do include the folder name, all interpolations of form "<folder name>/<lastpass secret that contains spaces in its identifier>" fail

**Comment by Polar-Beard** [comment]
Any chance we could see the pipeline yaml that you're running this against? We'd like to be able to test it out ourselves, since running it against our own pipeline is working as expected.

**Comment by Polar-Beard** [comment]
We ran a test using the following yaml

```
key: ((test-note/Notes))
```

`test-note` does not exist in a folder. On the first pass of this, it failed. We logged out of the `lpass` cli, then logged back in, and it worked. This leads us to believe this is an issue of lpass being out of sync, and unfortunately `lpass sync` does not resolve the issue, only a fresh login does. 

We use the command `lpass ls <your-credential>` to do an existence check on the credential. Could you verify whether or not that returns a value for one of your credentials? If it doesn't, could you try logging out of the lpass cli and logging back in and see if that changes anything?

Just want to note that we acknowledge that our existence check is flaky, so open to that criticism.

**Comment by genevieve** [comment]
Hey @thausler786. Are you still open to this PR?

**Comment by jsampson1** [comment]
Reconfigure-pipeline is now deprecated in favor of Concourse's built-in [credential management](https://concourse-ci.org/creds.html) support

**Pull request closed without merging**
